version: '3'
services:
  postgres_svr:
    image: postgres:15.6
    container_name: postgres_hcm
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    environment:
      POSTGRES_DB: bitrust_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA@
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  db-data:
